close all;
clear;

subjects_dir = '../data/coregistration';
system('mkdir figures/48surf');

Subjects = {...
    'sub1',...
    'sub2',...
    'sub3',...
    'sub4',...
    'sub5',...
    'sub6',...
    'sub7',...
    'sub8',...
    'sub9',...
    'sub10',...
    'sub11',...
    'sub12',...
    'sub13',...
    'sub14',...
    'sub15',...
    'sub16',...
    'sub17',...
    'sub18',...
    'sub19',...
    'sub20',...
    'sub21',...
    'sub22',...
    'sub23',...
    'sub24',...
    'sub25',...
    'sub26',...
    'sub27',...
    'sub28',...
    'sub29',...
    'sub30',...
    'sub31',...
    'sub32',...
    'sub33',...
    'sub34',...
    'sub35',...
    'sub36',...
    'sub37',...
    'sub38',...
    'sub39',...
    'sub40',...
    'sub41',...
    'sub42',...
    'sub43',...
    'sub44',...
    'sub45',...
    'sub46',...
    'sub47',...
    'sub48'...
};

const_col_surface = 0.90*[1 1 1];
const_alpha_surface = 1;
const_elec_surface = 0*[1 1 1];
const_elec_low = 0.4*[1 1 1];

h = figure('visible','off','Units','pixels','Position',[0 0 1920 1080]);
[ha, pos] = tight_subplot(6,8,[.01 .01],[.01 .01],[.01 .01]);

hold all;

n_chan_all = [];

for i = 1:length(Subjects)

    sid = Subjects{i};
    axes(ha(i));
    
    
    % Get hemi
    fn_en = sprintf('%s/%s/elec_recon/%s.electrodeNames',subjects_dir,sid,sid);
    if (~exist(fn_en,'file'))
        fprintf(2,'E: Did not find file: %s\n',fn_en);
    end
    f_en = fopen(fn_en,'r');
    En = textscan(f_en,'%s','Delimiter','\n','HeaderLines',2);
    En = En{1};
    hemi = lower(En{1}(end));
    fclose(f_en);
    
    % Read surf
    surface_type = 'pial';
    [s_vert, faces] = read_surf(sprintf('%s/%s/surf/%sh.%s',subjects_dir,sid,hemi,surface_type));
    
    % Get electrodes
    l = read_label(sprintf('%s/%s',subjects_dir,sid),sprintf('all_surf_ielvis'));
    if (isempty(l))
        fprintf('trying fallback directory..\n')
        l = read_label(sprintf('%s',sid),sprintf('all_surf_ielvis'));
        if (~isempty(l))
            fprintf('[*] Fallback directory SUCCESS.\n')
        else
            fprintf('[!] Fallback directory FAILED.\n')
        end
    end
    [~,sIdx] = sort(l(:,end));
    l = l(sIdx,:); % zero-indexed
    [n_chan,~] = size(l);
    [Xe,Ye,Ze] = sphere(20);
    
    % Plot electrode
    const_elec_radius = 2;
    for i2 = 1:n_chan
        X = Xe*const_elec_radius + s_vert(l(i2,1)+1,1);
        Y = Ye*const_elec_radius + s_vert(l(i2,1)+1,2);
        Z = Ze*const_elec_radius + s_vert(l(i2,1)+1,3);
        elec_pa_i = surf2patch(X,Y,Z);
        vert = elec_pa_i.vertices;
        q = trisurf(elec_pa_i.faces,vert(:,1),vert(:,2),vert(:,3),...
            'EdgeColor','none','FaceColor',const_elec_surface);
        hold on;
        q.SpecularStrength = 0;
        q.SpecularExponent = 1;
    end
    
    

    p = trisurf(faces+1,s_vert(:,1),s_vert(:,2),s_vert(:,3),...
        'EdgeColor','none','FaceColor',const_col_surface);
    brainlight;
%     daspect([1 1 1]);
%     p.AmbientStrength = 0.5 ;
%     p.DiffuseStrength = 0.5 ;
%     p.SpecularStrength = 0.2;
%     p.SpecularExponent = 1;
%     p.BackFaceLighting = 'lit';
%     p.FaceLighting = 'gouraud';
%     cam_elev = -15;
%     camlight(-135,cam_elev);
%     camlight(45,cam_elev);
%     %camlight(-225,cam_elev);
%     %camlight(-45,cam_elev);

    ax = gca;
    if (strcmp(hemi,'r'))
        x_t = ax.XLim(1);
        y_t = ax.YLim(2);
        view(90,0);
    else
        x_t = ax.XLim(1);
        y_t = (-1) * ax.YLim(2);
        view(-90,0);
    end
    axis off
    
    x_t = 0;%ax.Position(1);
    y_t = 0;%ax.Position(4);
    
%     text(x_t,y_t,sprintf('%i',str2double(sid(2:end))),'Units','Normalized',...
%         'HorizontalAlignment','left');
    
    if (i == 8)
        %break
    end
    
    n_chan_all = [n_chan_all, n_chan];

end


p_name = sprintf('figures/48surf/all_nchan-%i_mean-%i_std-%i_anon',...
    sum(n_chan_all),round(mean(n_chan_all)),round(std(n_chan_all)));
print(h,p_name,'-depsc');
print(h,p_name,'-djpeg','-r300');
print(h,p_name,'-dpng','-r600');
